### ISSUE TITLE
issue with outdated illuminate/contracts requirement

### ISSUE THREAD

**Issue by idealerror** [RPillz/laravel-feature-access#1]
Hello,

This looks like a great package and fits with a project I'm working on.  

I'm running into an issue with `illuminate/contracts` in your composer.json requirements:

```
 Problem 1
    - Root composer.json requires rpillz/laravel-feature-access ^1.0 -> satisfiable by rpillz/laravel-feature-access[1.0.0, 1.0.1].
    - rpillz/laravel-feature-access[1.0.0, ..., 1.0.1] require illuminate/contracts ^8.37 -> found illuminate/contracts[v8.37.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.17).
```

I'm running Laravel 9.17.0

**Comment by RPillz** [comment]
Thanks Chris! Pardon the long wait but I have updated the package to work with Laravel 9.
